# Generated by Django 4.2.30 on 2026-07-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
